"""empty message

Revision ID: 71f809076cbd
Revises: ae2c9dc788fe
Create Date: 2020-02-19 21:04:24.171979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f809076cbd'
down_revision = 'ae2c9dc788fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('color', sa.String(), nullable=True))
    op.add_column('versions', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('works', sa.Column('newest_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'newest_version')
    op.drop_column('versions', 'number')
    op.drop_column('versions', 'color')
    # ### end Alembic commands ###
