"""empty message

Revision ID: cbe1c73a56e5
Revises: 71f809076cbd
Create Date: 2020-02-21 11:28:43.720535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe1c73a56e5'
down_revision = '71f809076cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'title')
    # ### end Alembic commands ###
